// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static class MVC {
    public static FODT.Controllers.AdminController Admin = new FODT.Controllers.T4MVC_AdminController();
    public static FODT.Controllers.AwardsController Awards = new FODT.Controllers.T4MVC_AwardsController();
    public static FODT.Controllers.HomeController Home = new FODT.Controllers.T4MVC_HomeController();
    public static FODT.Controllers.MediaController Media = new FODT.Controllers.T4MVC_MediaController();
    public static FODT.Controllers.PersonController Person = new FODT.Controllers.T4MVC_PersonController();
    public static FODT.Controllers.SearchController Search = new FODT.Controllers.T4MVC_SearchController();
    public static FODT.Controllers.ShowController Show = new FODT.Controllers.T4MVC_ShowController();
    public static FODT.Controllers.ShowsController Shows = new FODT.Controllers.T4MVC_ShowsController();
    public static FODT.Controllers.ToasterController Toaster = new FODT.Controllers.T4MVC_ToasterController();
    public static FODT.Controllers.UserController User = new FODT.Controllers.T4MVC_UserController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC {
}

   
namespace System.Web.Mvc {
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class T4Extensions {
        public static MvcHtmlString ActionLink(this HtmlHelper htmlHelper, string linkText, ActionResult result) {
            return htmlHelper.ActionLink(linkText, result, null, null, null, null);
        }

        public static MvcHtmlString ActionLink(this HtmlHelper htmlHelper, string linkText, ActionResult result, object htmlAttributes, string protocol = null, string hostName = null, string fragment = null) {
            return htmlHelper.RouteLink(linkText, null, protocol ?? result.GetT4MVCResult().Protocol, hostName, fragment, result.GetRouteValueDictionary(), HtmlHelper.AnonymousObjectToHtmlAttributes(htmlAttributes));
        }

        public static MvcHtmlString ActionLink(this HtmlHelper htmlHelper, string linkText, ActionResult result, IDictionary<string, object> htmlAttributes, string protocol = null, string hostName = null, string fragment = null) {
            return htmlHelper.RouteLink(linkText, null, protocol ?? result.GetT4MVCResult().Protocol, hostName, fragment, result.GetRouteValueDictionary(), htmlAttributes);
        }

        public static MvcForm BeginForm(this HtmlHelper htmlHelper, ActionResult result) {
            return htmlHelper.BeginForm(result, FormMethod.Post);
        }

        public static MvcForm BeginForm(this HtmlHelper htmlHelper, ActionResult result, FormMethod formMethod) {
            return htmlHelper.BeginForm(result, formMethod, null);
        }

        public static MvcForm BeginForm(this HtmlHelper htmlHelper, ActionResult result, FormMethod formMethod, object htmlAttributes) {
            return BeginForm(htmlHelper, result, formMethod, HtmlHelper.AnonymousObjectToHtmlAttributes(htmlAttributes));
        }

        public static MvcForm BeginForm(this HtmlHelper htmlHelper, ActionResult result, FormMethod formMethod, IDictionary<string, object> htmlAttributes) {
            var callInfo = result.GetT4MVCResult();
            return htmlHelper.BeginForm(callInfo.Action, callInfo.Controller, callInfo.RouteValueDictionary, formMethod, htmlAttributes);
        }

        public static void RenderAction(this HtmlHelper htmlHelper, ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            htmlHelper.RenderAction(callInfo.Action, callInfo.Controller, callInfo.RouteValueDictionary);
        }

        public static MvcHtmlString Action(this HtmlHelper htmlHelper, ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return htmlHelper.Action(callInfo.Action, callInfo.Controller, callInfo.RouteValueDictionary);
        }

        public static string Action(this UrlHelper urlHelper, ActionResult result) {
            return urlHelper.Action(result, null, null);
        }

        public static string Action(this UrlHelper urlHelper, ActionResult result, string protocol = null, string hostName = null) {
            return urlHelper.RouteUrl(null, result.GetRouteValueDictionary(), protocol ?? result.GetT4MVCResult().Protocol, hostName);
        }

        public static string ActionAbsolute(this UrlHelper urlHelper, ActionResult result) {
            return string.Format("{0}{1}",urlHelper.RequestContext.HttpContext.Request.Url.GetLeftPart(UriPartial.Authority),
                urlHelper.RouteUrl(result.GetRouteValueDictionary()));
        }

        public static MvcHtmlString ActionLink(this AjaxHelper ajaxHelper, string linkText, ActionResult result, AjaxOptions ajaxOptions) {
            return ajaxHelper.RouteLink(linkText, result.GetRouteValueDictionary(), ajaxOptions);
        }

        public static MvcHtmlString ActionLink(this AjaxHelper ajaxHelper, string linkText, ActionResult result, AjaxOptions ajaxOptions, object htmlAttributes) {
            return ajaxHelper.RouteLink(linkText, result.GetRouteValueDictionary(), ajaxOptions, HtmlHelper.AnonymousObjectToHtmlAttributes(htmlAttributes));
        }

        public static MvcHtmlString ActionLink(this AjaxHelper ajaxHelper, string linkText, ActionResult result, AjaxOptions ajaxOptions, IDictionary<string, object> htmlAttributes) {
            return ajaxHelper.RouteLink(linkText, result.GetRouteValueDictionary(), ajaxOptions, htmlAttributes);
        }

        public static MvcForm BeginForm(this AjaxHelper ajaxHelper, ActionResult result, AjaxOptions ajaxOptions) {
            return ajaxHelper.BeginForm(result, ajaxOptions, null);
        }

        public static MvcForm BeginForm(this AjaxHelper ajaxHelper, ActionResult result, AjaxOptions ajaxOptions, object htmlAttributes) {
            return BeginForm(ajaxHelper, result, ajaxOptions, HtmlHelper.AnonymousObjectToHtmlAttributes(htmlAttributes));
        }

        public static MvcForm BeginForm(this AjaxHelper ajaxHelper, ActionResult result, AjaxOptions ajaxOptions, IDictionary<string, object> htmlAttributes) {
            var callInfo = result.GetT4MVCResult();
            return ajaxHelper.BeginForm(callInfo.Action, callInfo.Controller, callInfo.RouteValueDictionary, ajaxOptions, htmlAttributes);
        }

        public static Route MapRoute(this RouteCollection routes, string name, string url, ActionResult result) {
            return MapRoute(routes, name, url, result, null /*namespaces*/);
        }

        public static Route MapRoute(this RouteCollection routes, string name, string url, ActionResult result, object defaults) {
            return MapRoute(routes, name, url, result, defaults, null /*constraints*/, null /*namespaces*/);
        }

        public static Route MapRoute(this RouteCollection routes, string name, string url, ActionResult result, string[] namespaces) {
            return MapRoute(routes, name, url, result, null /*defaults*/, namespaces);
        }

        public static Route MapRoute(this RouteCollection routes, string name, string url, ActionResult result, object defaults, object constraints) {
            return MapRoute(routes, name, url, result, defaults, constraints, null /*namespaces*/);
        }

        public static Route MapRoute(this RouteCollection routes, string name, string url, ActionResult result, object defaults, string[] namespaces) {
            return MapRoute(routes, name, url, result, defaults, null /*constraints*/, namespaces);
        }

        public static Route MapRoute(this RouteCollection routes, string name, string url, ActionResult result, object defaults, object constraints, string[] namespaces) {
            // Create and add the route
            var route = CreateRoute(url, result, defaults, constraints, namespaces);
            routes.Add(name, route);
            return route;
        }

        // Note: can't name the AreaRegistrationContext methods 'MapRoute', as that conflicts with the existing methods
        public static Route MapRouteArea(this AreaRegistrationContext context, string name, string url, ActionResult result) {
            return MapRouteArea(context, name, url, result, null /*namespaces*/);
        }

        public static Route MapRouteArea(this AreaRegistrationContext context, string name, string url, ActionResult result, object defaults) {
            return MapRouteArea(context, name, url, result, defaults, null /*constraints*/, null /*namespaces*/);
        }

        public static Route MapRouteArea(this AreaRegistrationContext context, string name, string url, ActionResult result, string[] namespaces) {
            return MapRouteArea(context, name, url, result, null /*defaults*/, namespaces);
        }

        public static Route MapRouteArea(this AreaRegistrationContext context, string name, string url, ActionResult result, object defaults, object constraints) {
            return MapRouteArea(context, name, url, result, defaults, constraints, null /*namespaces*/);
        }

        public static Route MapRouteArea(this AreaRegistrationContext context, string name, string url, ActionResult result, object defaults, string[] namespaces) {
            return MapRouteArea(context, name, url, result, defaults, null /*constraints*/, namespaces);
        }

        public static Route MapRouteArea(this AreaRegistrationContext context, string name, string url, ActionResult result, object defaults, object constraints, string[] namespaces) {
            // Create and add the route
            if ((namespaces == null) && (context.Namespaces != null)) {
                 namespaces = context.Namespaces.ToArray();
            }
            var route = CreateRoute(url, result, defaults, constraints, namespaces);
            context.Routes.Add(name, route);
            route.DataTokens["area"] = context.AreaName;
            bool useNamespaceFallback = (namespaces == null) || (namespaces.Length == 0);
            route.DataTokens["UseNamespaceFallback"] = useNamespaceFallback;
            return route;
        }

        private static Route CreateRoute(string url, ActionResult result, object defaults, object constraints, string[] namespaces) {
            // Start by adding the default values from the anonymous object (if any)
            var routeValues = new RouteValueDictionary(defaults);

            // Then add the Controller/Action names and the parameters from the call
            foreach (var pair in result.GetRouteValueDictionary()) {
                routeValues.Add(pair.Key, pair.Value);
            }

            var routeConstraints = new RouteValueDictionary(constraints);

            // Create and add the route
            var route = new Route(url, routeValues, routeConstraints, new MvcRouteHandler());

            route.DataTokens = new RouteValueDictionary();

            if (namespaces != null && namespaces.Length > 0) {
                route.DataTokens["Namespaces"] = namespaces;
            }

            return route;
        }

        public static IT4MVCActionResult GetT4MVCResult(this ActionResult result) {
            var t4MVCResult = result as IT4MVCActionResult;
            if (t4MVCResult == null) {
                throw new InvalidOperationException("T4MVC was called incorrectly. You may need to force it to regenerate by right clicking on T4MVC.tt and choosing Run Custom Tool");
            }
            return t4MVCResult;
        }

        public static RouteValueDictionary GetRouteValueDictionary(this ActionResult result) {
            return result.GetT4MVCResult().RouteValueDictionary;
        }

        public static ActionResult AddRouteValues(this ActionResult result, object routeValues) {
            return result.AddRouteValues(new RouteValueDictionary(routeValues));
        }

        public static ActionResult AddRouteValues(this ActionResult result, RouteValueDictionary routeValues) {
            RouteValueDictionary currentRouteValues = result.GetRouteValueDictionary();

            // Add all the extra values
            foreach (var pair in routeValues) {
                ModelUnbinderHelpers.AddRouteValues(currentRouteValues, pair.Key, pair.Value);
            }

            return result;
        }

        public static ActionResult AddRouteValues(this ActionResult result, System.Collections.Specialized.NameValueCollection nameValueCollection) {
            // Copy all the values from the NameValueCollection into the route dictionary
            nameValueCollection.CopyTo(result.GetRouteValueDictionary());
            return result;
        }

        public static ActionResult AddRouteValue(this ActionResult result, string name, object value) {
            RouteValueDictionary routeValues = result.GetRouteValueDictionary();
            ModelUnbinderHelpers.AddRouteValues(routeValues, name, value);
            return result;
        }
        
        public static void InitMVCT4Result(this IT4MVCActionResult result, string area, string controller, string action, string protocol = null) {
            result.Controller = controller;
            result.Action = action;
            result.Protocol = T4MVCHelpers.IsProduction() ? protocol : null;
            result.RouteValueDictionary = new RouteValueDictionary();
            result.RouteValueDictionary.Add("Area", area ?? "");
            result.RouteValueDictionary.Add("Controller", controller);
            result.RouteValueDictionary.Add("Action", action);
        }

        public static bool FileExists(string virtualPath) {
            if (!HostingEnvironment.IsHosted) return false;
            string filePath = HostingEnvironment.MapPath(virtualPath);
            return System.IO.File.Exists(filePath);
        }

        static DateTime CenturyBegin=new DateTime(2001,1,1);
        public static string TimestampString(string virtualPath) {
            if (!HostingEnvironment.IsHosted) return string.Empty;
            string filePath = HostingEnvironment.MapPath(virtualPath);
            return Convert.ToString((System.IO.File.GetLastWriteTimeUtc(filePath).Ticks-CenturyBegin.Ticks)/1000000000,16);            
        }
    }
}



namespace T4MVC {
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}


  

   
[GeneratedCode("T4MVC", "2.0")]   
public interface IT4MVCActionResult {   
    string Action { get; set; }   
    string Controller { get; set; }   
    RouteValueDictionary RouteValueDictionary { get; set; } 
    string Protocol {get; set; }  
}   
  

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public class T4MVC_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult {
    public T4MVC_ActionResult(string area, string controller, string action, string protocol = null): base()  {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links {
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Assets {
        private const string URLPATH = "~/Assets";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class css {
            private const string URLPATH = "~/Assets/css";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
                 
            public static readonly string fodt_components_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/fodt-components.min.css") ? Url("fodt-components.min.css") : Url("fodt-components.css");
                 
            public static readonly string fodt_forms_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/fodt-forms.min.css") ? Url("fodt-forms.min.css") : Url("fodt-forms.css");
                 
            public static readonly string fodt_main_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/fodt-main.min.css") ? Url("fodt-main.min.css") : Url("fodt-main.css");
                 
            public static readonly string fodt_slideshow_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/fodt-slideshow.min.css") ? Url("fodt-slideshow.min.css") : Url("fodt-slideshow.css");
                 
            public static readonly string fodt_tables_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/fodt-tables.min.css") ? Url("fodt-tables.min.css") : Url("fodt-tables.css");
                 
        }
    
        public static readonly string dtstyle_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/dtstyle.min.css") ? Url("dtstyle.min.css") : Url("dtstyle.css");
             
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class fonts {
            private const string URLPATH = "~/Assets/fonts";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string glyphicons_halflings_regular_eot = Url("glyphicons-halflings-regular.eot");
            public static readonly string glyphicons_halflings_regular_svg = Url("glyphicons-halflings-regular.svg");
            public static readonly string glyphicons_halflings_regular_ttf = Url("glyphicons-halflings-regular.ttf");
            public static readonly string glyphicons_halflings_regular_woff = Url("glyphicons-halflings-regular.woff");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class img {
            private const string URLPATH = "~/Assets/img";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string ajax_loader_gif = Url("ajax-loader.gif");
            public static readonly string bkup_imdtlogo_png = Url("bkup.imdtlogo.png");
            public static readonly string bulletRelatedLinks_gif = Url("bulletRelatedLinks.gif");
            public static readonly string dtlogo_png = Url("dtlogo.png");
            public static readonly string dttitle_png = Url("dttitle.png");
            public static readonly string facebook_16_png = Url("facebook_16.png");
            public static readonly string facebook_32_png = Url("facebook_32.png");
            public static readonly string facebook_signin_png = Url("facebook_signin.png");
            public static readonly string fb_icon_gif = Url("fb-icon.gif");
            public static readonly string greg_abbott_jpg = Url("greg_abbott.jpg");
            public static readonly string header_png = Url("header.png");
            public static readonly string imdtlogo_png = Url("imdtlogo.png");
            public static readonly string imdtlogosmall_png = Url("imdtlogosmall.png");
            public static readonly string imdtlogotrans_png = Url("imdtlogotrans.png");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class layout {
                private const string URLPATH = "~/Assets/img/layout";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string home_bg_jpg = Url("home-bg.jpg");
                public static readonly string home_header_png = Url("home-header.png");
                public static readonly string inside_bg_jpg = Url("inside-bg.jpg");
                public static readonly string inside_header_png = Url("inside-header.png");
                public static readonly string logo_png = Url("logo.png");
            }
        
            public static readonly string nopic_gif = Url("nopic.gif");
            public static readonly string nopicind_gif = Url("nopicind.gif");
            public static readonly string noposter_gif = Url("noposter.gif");
            public static readonly string rss_icon_gif = Url("rss-icon.gif");
            public static readonly string showall_png = Url("showall.png");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class slider {
                private const string URLPATH = "~/Assets/img/slider";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string slider_fodt_jpg = Url("slider-fodt.jpg");
                public static readonly string slider_football_jpg = Url("slider-football.jpg");
            }
        
            public static readonly string tinyposter_gif = Url("tinyposter.gif");
            public static readonly string twitter_icon_gif = Url("twitter-icon.gif");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class js {
            private const string URLPATH = "~/Assets/js";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string fodt_common_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/fodt.common.min.js") ? Url("fodt.common.min.js") : Url("fodt.common.js");
                          
            public static readonly string fodt_polyfill_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/fodt.polyfill.min.js") ? Url("fodt.polyfill.min.js") : Url("fodt.polyfill.js");
                          
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class lib {
                private const string URLPATH = "~/Assets/js/lib";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.js") ? Url("bootstrap.min.js") : Url("bootstrap.js");
                              
                public static readonly string jquery_2_1_3_min_js = Url("jquery-2.1.3.min.js");
                public static readonly string jsrender_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jsrender.min.js") ? Url("jsrender.min.js") : Url("jsrender.js");
                              
                public static readonly string typeahead_jquery_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/typeahead.jquery.min.js") ? Url("typeahead.jquery.min.js") : Url("typeahead.jquery.js");
                              
            }
        
        }
    
    }

}

public static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;


    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}


namespace FODT.Controllers {
    public partial class AdminController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AdminController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AdminController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AdminController Actions { get { return MVC.Admin; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Admin";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string UsersList = "UsersList";
            public readonly string PeopleList = "PeopleList";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string Index = "Index";
            public const string UsersList = "UsersList";
            public const string PeopleList = "PeopleList";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string _AdminLayout = "~/Views/Admin/_AdminLayout.cshtml";
            public readonly string Index = "~/Views/Admin/Index.cshtml";
            public readonly string PeopleList = "~/Views/Admin/PeopleList.cshtml";
            public readonly string UsersList = "~/Views/Admin/UsersList.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_AdminController: FODT.Controllers.AdminController {
        public T4MVC_AdminController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult UsersList() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.UsersList);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult PeopleList() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.PeopleList);
            return callInfo;
        }

    }
}

namespace FODT.Controllers {
    public partial class AwardsController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AwardsController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AwardsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ByYear() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ByYear);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AwardsController Actions { get { return MVC.Awards; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Awards";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Awards";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string ByYear = "ByYear";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string ByYear = "ByYear";
        }


        static readonly ActionParamsClass_ByYear s_params_ByYear = new ActionParamsClass_ByYear();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ByYear ByYearParams { get { return s_params_ByYear; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ByYear {
            public readonly string year = "year";
        }
        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string ByYear = "~/Views/Awards/ByYear.cshtml";
            public readonly string ByYearViewModel = "~/Views/Awards/ByYearViewModel.cs";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_AwardsController: FODT.Controllers.AwardsController {
        public T4MVC_AwardsController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult ByYear(short? year) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ByYear);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "year", year);
            return callInfo;
        }

    }
}

namespace FODT.Controllers {
    public partial class HomeController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected HomeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Admin_EditPerson() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Admin_EditPerson);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Admin_ShowPerson() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Admin_ShowPerson);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController Actions { get { return MVC.Home; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Home";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Welcome = "Welcome";
            public readonly string Index = "Index";
            public readonly string Admin_EditPerson = "Admin_EditPerson";
            public readonly string Admin_ShowPerson = "Admin_ShowPerson";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string Welcome = "Welcome";
            public const string Index = "Index";
            public const string Admin_EditPerson = "Admin_EditPerson";
            public const string Admin_ShowPerson = "Admin_ShowPerson";
        }


        static readonly ActionParamsClass_Admin_EditPerson s_params_Admin_EditPerson = new ActionParamsClass_Admin_EditPerson();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Admin_EditPerson Admin_EditPersonParams { get { return s_params_Admin_EditPerson; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Admin_EditPerson {
            public readonly string personId = "personId";
        }
        static readonly ActionParamsClass_Admin_ShowPerson s_params_Admin_ShowPerson = new ActionParamsClass_Admin_ShowPerson();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Admin_ShowPerson Admin_ShowPersonParams { get { return s_params_Admin_ShowPerson; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Admin_ShowPerson {
            public readonly string showId = "showId";
        }
        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string Admin = "~/Views/Home/Admin.cshtml";
            public readonly string AdminViewModel = "~/Views/Home/AdminViewModel.cs";
            public readonly string Index = "~/Views/Home/Index.cshtml";
            public readonly string Welcome = "~/Views/Home/Welcome.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_HomeController: FODT.Controllers.HomeController {
        public T4MVC_HomeController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Welcome() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Welcome);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Admin_EditPerson(int personId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Admin_EditPerson);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personId", personId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Admin_ShowPerson(int showId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Admin_ShowPerson);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "showId", showId);
            return callInfo;
        }

    }
}

namespace FODT.Controllers {
    public partial class MediaController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public MediaController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected MediaController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Tag() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Tag);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult GetItem() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.GetItem);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult GetItemTiny() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.GetItemTiny);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult GetItemThumbnail() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.GetItemThumbnail);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult GetItemDetail() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.GetItemDetail);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public MediaController Actions { get { return MVC.Media; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Media";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Media";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Upload = "Upload";
            public readonly string Tag = "Tag";
            public readonly string GetItem = "GetItem";
            public readonly string GetItemTiny = "GetItemTiny";
            public readonly string GetItemThumbnail = "GetItemThumbnail";
            public readonly string GetItemDetail = "GetItemDetail";
            public readonly string Index = "Index";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string Upload = "Upload";
            public const string Tag = "Tag";
            public const string GetItem = "GetItem";
            public const string GetItemTiny = "GetItemTiny";
            public const string GetItemThumbnail = "GetItemThumbnail";
            public const string GetItemDetail = "GetItemDetail";
            public const string Index = "Index";
        }


        static readonly ActionParamsClass_Tag s_params_Tag = new ActionParamsClass_Tag();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Tag TagParams { get { return s_params_Tag; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Tag {
            public readonly string id = "id";
            public readonly string personId = "personId";
            public readonly string showId = "showId";
        }
        static readonly ActionParamsClass_GetItem s_params_GetItem = new ActionParamsClass_GetItem();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetItem GetItemParams { get { return s_params_GetItem; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetItem {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_GetItemTiny s_params_GetItemTiny = new ActionParamsClass_GetItemTiny();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetItemTiny GetItemTinyParams { get { return s_params_GetItemTiny; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetItemTiny {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_GetItemThumbnail s_params_GetItemThumbnail = new ActionParamsClass_GetItemThumbnail();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetItemThumbnail GetItemThumbnailParams { get { return s_params_GetItemThumbnail; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetItemThumbnail {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_GetItemDetail s_params_GetItemDetail = new ActionParamsClass_GetItemDetail();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetItemDetail GetItemDetailParams { get { return s_params_GetItemDetail; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetItemDetail {
            public readonly string id = "id";
        }
        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string GetItemDetail = "~/Views/Media/GetItemDetail.cshtml";
            public readonly string GetItemDetailViewModel = "~/Views/Media/GetItemDetailViewModel.cs";
            public readonly string Index = "~/Views/Media/Index.cshtml";
            public readonly string IndexViewModel = "~/Views/Media/IndexViewModel.cs";
            public readonly string Upload = "~/Views/Media/Upload.cshtml";
            public readonly string UploadViewModel = "~/Views/Media/UploadViewModel.cs";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_MediaController: FODT.Controllers.MediaController {
        public T4MVC_MediaController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Upload() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Upload);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Upload(FODT.Controllers.MediaController.UploadPOSTParameters param) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Upload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "param", param);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Tag(int id, int? personId, int? showId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Tag);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personId", personId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "showId", showId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetItem(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetItem);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetItemTiny(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetItemTiny);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetItemThumbnail(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetItemThumbnail);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetItemDetail(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetItemDetail);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

    }
}

namespace FODT.Controllers {
    public partial class PersonController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PersonController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PersonController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult PersonDetails() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.PersonDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ListPersonMedia() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ListPersonMedia);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult GetPersonMedia() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.GetPersonMedia);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SaveNew() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SaveNew);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult EditPerson() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.EditPerson);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SaveEdit() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SaveEdit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ChangeDefaultMediaItem() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ChangeDefaultMediaItem);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AddAward() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AddAward);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult DeleteAward() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.DeleteAward);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AddClubPosition() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AddClubPosition);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult DeleteClubPosition() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.DeleteClubPosition);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AddCast() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AddCast);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult DeleteCast() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.DeleteCast);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AddCrew() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AddCrew);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult DeleteCrew() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.DeleteCrew);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PersonController Actions { get { return MVC.Person; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Person";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Person";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string PersonDetails = "PersonDetails";
            public readonly string ListPersonMedia = "ListPersonMedia";
            public readonly string GetPersonMedia = "GetPersonMedia";
            public readonly string New = "New";
            public readonly string SaveNew = "SaveNew";
            public readonly string EditPerson = "EditPerson";
            public readonly string SaveEdit = "SaveEdit";
            public readonly string ChangeDefaultMediaItem = "ChangeDefaultMediaItem";
            public readonly string AddAward = "AddAward";
            public readonly string DeleteAward = "DeleteAward";
            public readonly string AddClubPosition = "AddClubPosition";
            public readonly string DeleteClubPosition = "DeleteClubPosition";
            public readonly string AddCast = "AddCast";
            public readonly string DeleteCast = "DeleteCast";
            public readonly string AddCrew = "AddCrew";
            public readonly string DeleteCrew = "DeleteCrew";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string PersonDetails = "PersonDetails";
            public const string ListPersonMedia = "ListPersonMedia";
            public const string GetPersonMedia = "GetPersonMedia";
            public const string New = "New";
            public const string SaveNew = "SaveNew";
            public const string EditPerson = "EditPerson";
            public const string SaveEdit = "SaveEdit";
            public const string ChangeDefaultMediaItem = "ChangeDefaultMediaItem";
            public const string AddAward = "AddAward";
            public const string DeleteAward = "DeleteAward";
            public const string AddClubPosition = "AddClubPosition";
            public const string DeleteClubPosition = "DeleteClubPosition";
            public const string AddCast = "AddCast";
            public const string DeleteCast = "DeleteCast";
            public const string AddCrew = "AddCrew";
            public const string DeleteCrew = "DeleteCrew";
        }


        static readonly ActionParamsClass_PersonDetails s_params_PersonDetails = new ActionParamsClass_PersonDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PersonDetails PersonDetailsParams { get { return s_params_PersonDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PersonDetails {
            public readonly string personId = "personId";
        }
        static readonly ActionParamsClass_ListPersonMedia s_params_ListPersonMedia = new ActionParamsClass_ListPersonMedia();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ListPersonMedia ListPersonMediaParams { get { return s_params_ListPersonMedia; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ListPersonMedia {
            public readonly string personId = "personId";
        }
        static readonly ActionParamsClass_GetPersonMedia s_params_GetPersonMedia = new ActionParamsClass_GetPersonMedia();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetPersonMedia GetPersonMediaParams { get { return s_params_GetPersonMedia; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetPersonMedia {
            public readonly string personId = "personId";
            public readonly string mediaItemId = "mediaItemId";
        }
        static readonly ActionParamsClass_SaveNew s_params_SaveNew = new ActionParamsClass_SaveNew();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveNew SaveNewParams { get { return s_params_SaveNew; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveNew {
            public readonly string param = "param";
        }
        static readonly ActionParamsClass_EditPerson s_params_EditPerson = new ActionParamsClass_EditPerson();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditPerson EditPersonParams { get { return s_params_EditPerson; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditPerson {
            public readonly string personId = "personId";
        }
        static readonly ActionParamsClass_SaveEdit s_params_SaveEdit = new ActionParamsClass_SaveEdit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveEdit SaveEditParams { get { return s_params_SaveEdit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveEdit {
            public readonly string personId = "personId";
            public readonly string param = "param";
        }
        static readonly ActionParamsClass_ChangeDefaultMediaItem s_params_ChangeDefaultMediaItem = new ActionParamsClass_ChangeDefaultMediaItem();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ChangeDefaultMediaItem ChangeDefaultMediaItemParams { get { return s_params_ChangeDefaultMediaItem; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ChangeDefaultMediaItem {
            public readonly string personId = "personId";
            public readonly string mediaItemId = "mediaItemId";
        }
        static readonly ActionParamsClass_AddAward s_params_AddAward = new ActionParamsClass_AddAward();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddAward AddAwardParams { get { return s_params_AddAward; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddAward {
            public readonly string personId = "personId";
        }
        static readonly ActionParamsClass_DeleteAward s_params_DeleteAward = new ActionParamsClass_DeleteAward();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteAward DeleteAwardParams { get { return s_params_DeleteAward; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteAward {
            public readonly string personId = "personId";
            public readonly string personAwardId = "personAwardId";
            public readonly string showAwardId = "showAwardId";
        }
        static readonly ActionParamsClass_AddClubPosition s_params_AddClubPosition = new ActionParamsClass_AddClubPosition();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddClubPosition AddClubPositionParams { get { return s_params_AddClubPosition; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddClubPosition {
            public readonly string personId = "personId";
        }
        static readonly ActionParamsClass_DeleteClubPosition s_params_DeleteClubPosition = new ActionParamsClass_DeleteClubPosition();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteClubPosition DeleteClubPositionParams { get { return s_params_DeleteClubPosition; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteClubPosition {
            public readonly string personId = "personId";
            public readonly string personClubPositionId = "personClubPositionId";
        }
        static readonly ActionParamsClass_AddCast s_params_AddCast = new ActionParamsClass_AddCast();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddCast AddCastParams { get { return s_params_AddCast; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddCast {
            public readonly string personId = "personId";
        }
        static readonly ActionParamsClass_DeleteCast s_params_DeleteCast = new ActionParamsClass_DeleteCast();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteCast DeleteCastParams { get { return s_params_DeleteCast; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteCast {
            public readonly string personId = "personId";
            public readonly string showCastId = "showCastId";
        }
        static readonly ActionParamsClass_AddCrew s_params_AddCrew = new ActionParamsClass_AddCrew();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddCrew AddCrewParams { get { return s_params_AddCrew; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddCrew {
            public readonly string personId = "personId";
        }
        static readonly ActionParamsClass_DeleteCrew s_params_DeleteCrew = new ActionParamsClass_DeleteCrew();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteCrew DeleteCrewParams { get { return s_params_DeleteCrew; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteCrew {
            public readonly string personId = "personId";
            public readonly string showCrewId = "showCrewId";
        }
        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string AddAward = "~/Views/Person/AddAward.cshtml";
            public readonly string AddClubPosition = "~/Views/Person/AddClubPosition.cshtml";
            public readonly string EditPerson = "~/Views/Person/EditPerson.cshtml";
            public readonly string EditPersonViewModel = "~/Views/Person/EditPersonViewModel.cs";
            public readonly string GetPersonMedia = "~/Views/Person/GetPersonMedia.cshtml";
            public readonly string GetPersonMediaViewModel = "~/Views/Person/GetPersonMediaViewModel.cs";
            public readonly string ListPersonMedia = "~/Views/Person/ListPersonMedia.cshtml";
            public readonly string ListPersonMediaViewModel = "~/Views/Person/ListPersonMediaViewModel.cs";
            public readonly string PersonDetails = "~/Views/Person/PersonDetails.cshtml";
            public readonly string PersonDetailsViewModel = "~/Views/Person/PersonDetailsViewModel.cs";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_PersonController: FODT.Controllers.PersonController {
        public T4MVC_PersonController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult PersonDetails(int personId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.PersonDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personId", personId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ListPersonMedia(int personId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ListPersonMedia);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personId", personId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetPersonMedia(int personId, int mediaItemId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetPersonMedia);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personId", personId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mediaItemId", mediaItemId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult New() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.New);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SaveNew(FODT.Controllers.PersonController.SaveEditParameters param) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SaveNew);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "param", param);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult EditPerson(int personId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.EditPerson);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personId", personId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SaveEdit(int personId, FODT.Controllers.PersonController.SaveEditParameters param) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SaveEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personId", personId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "param", param);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ChangeDefaultMediaItem(int personId, int mediaItemId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ChangeDefaultMediaItem);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personId", personId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mediaItemId", mediaItemId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddAward(int personId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddAward);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personId", personId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddAward(int personId, int awardId, short year, int? showId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddAward);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personId", personId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "awardId", awardId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "year", year);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "showId", showId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult DeleteAward(int personId, int? personAwardId, int? showAwardId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.DeleteAward);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personId", personId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personAwardId", personAwardId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "showAwardId", showAwardId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddClubPosition(int personId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddClubPosition);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personId", personId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddClubPosition(int personId, string position, short year) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddClubPosition);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personId", personId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "position", position);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "year", year);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult DeleteClubPosition(int personId, int personClubPositionId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.DeleteClubPosition);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personId", personId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personClubPositionId", personClubPositionId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddCast(int personId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddCast);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personId", personId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddCast(int personId, int showId, string role) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddCast);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personId", personId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "showId", showId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "role", role);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult DeleteCast(int personId, int showCastId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.DeleteCast);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personId", personId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "showCastId", showCastId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddCrew(int personId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddCrew);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personId", personId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddCrew(int personId, int showId, string position) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddCrew);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personId", personId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "showId", showId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "position", position);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult DeleteCrew(int personId, int showCrewId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.DeleteCrew);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personId", personId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "showCrewId", showCrewId);
            return callInfo;
        }

    }
}

namespace FODT.Controllers {
    public partial class SearchController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SearchController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SearchController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Search() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Search);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SearchController Actions { get { return MVC.Search; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Search";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Search";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Search = "Search";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string Search = "Search";
        }


        static readonly ActionParamsClass_Search s_params_Search = new ActionParamsClass_Search();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Search SearchParams { get { return s_params_Search; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Search {
            public readonly string searchTerm = "searchTerm";
            public readonly string searchType = "searchType";
        }
        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string SearchResults = "~/Views/Search/SearchResults.cshtml";
            public readonly string SearchResultsViewModel = "~/Views/Search/SearchResultsViewModel.cs";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_SearchController: FODT.Controllers.SearchController {
        public T4MVC_SearchController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Search(string searchTerm, string searchType) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchTerm", searchTerm);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchType", searchType);
            return callInfo;
        }

    }
}

namespace FODT.Controllers {
    public partial class ShowController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ShowController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ShowController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Get() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Get);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ListShowMedia() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ListShowMedia);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult GetShowMedia() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.GetShowMedia);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ShowController Actions { get { return MVC.Show; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Show";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Show";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Get = "Get";
            public readonly string ListShowMedia = "ListShowMedia";
            public readonly string GetShowMedia = "GetShowMedia";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string Get = "Get";
            public const string ListShowMedia = "ListShowMedia";
            public const string GetShowMedia = "GetShowMedia";
        }


        static readonly ActionParamsClass_Get s_params_Get = new ActionParamsClass_Get();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Get GetParams { get { return s_params_Get; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Get {
            public readonly string showId = "showId";
        }
        static readonly ActionParamsClass_ListShowMedia s_params_ListShowMedia = new ActionParamsClass_ListShowMedia();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ListShowMedia ListShowMediaParams { get { return s_params_ListShowMedia; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ListShowMedia {
            public readonly string showId = "showId";
        }
        static readonly ActionParamsClass_GetShowMedia s_params_GetShowMedia = new ActionParamsClass_GetShowMedia();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetShowMedia GetShowMediaParams { get { return s_params_GetShowMedia; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetShowMedia {
            public readonly string showId = "showId";
            public readonly string mediaItemId = "mediaItemId";
        }
        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string Get = "~/Views/Show/Get.cshtml";
            public readonly string GetShowMedia = "~/Views/Show/GetShowMedia.cshtml";
            public readonly string GetShowMediaViewModel = "~/Views/Show/GetShowMediaViewModel.cs";
            public readonly string GetViewModel = "~/Views/Show/GetViewModel.cs";
            public readonly string ListShowMedia = "~/Views/Show/ListShowMedia.cshtml";
            public readonly string ListShowMediaViewModel = "~/Views/Show/ListShowMediaViewModel.cs";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ShowController: FODT.Controllers.ShowController {
        public T4MVC_ShowController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Get(int showId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Get);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "showId", showId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ListShowMedia(int showId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ListShowMedia);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "showId", showId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetShowMedia(int showId, int mediaItemId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetShowMedia);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "showId", showId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mediaItemId", mediaItemId);
            return callInfo;
        }

    }
}

namespace FODT.Controllers {
    public partial class ShowsController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ShowsController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ShowsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ShowsController Actions { get { return MVC.Shows; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Shows";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Shows";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string SortByYear = "SortByYear";
            public readonly string SortByTitle = "SortByTitle";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string SortByYear = "SortByYear";
            public const string SortByTitle = "SortByTitle";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string SortByTitle = "~/Views/Shows/SortByTitle.cshtml";
            public readonly string SortByYear = "~/Views/Shows/SortByYear.cshtml";
            public readonly string SortedShowsViewModel = "~/Views/Shows/SortedShowsViewModel.cs";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ShowsController: FODT.Controllers.ShowsController {
        public T4MVC_ShowsController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult SortByYear() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SortByYear);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SortByTitle() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SortByTitle);
            return callInfo;
        }

    }
}

namespace FODT.Controllers {
    public partial class ToasterController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ToasterController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ToasterController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ToasterController Actions { get { return MVC.Toaster; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Toaster";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Toaster";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Hunt = "Hunt";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string Hunt = "Hunt";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string Hunt = "~/Views/Toaster/Hunt.cshtml";
            public readonly string HuntViewModel = "~/Views/Toaster/HuntViewModel.cs";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ToasterController: FODT.Controllers.ToasterController {
        public T4MVC_ToasterController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Hunt() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Hunt);
            return callInfo;
        }

    }
}

namespace FODT.Controllers {
    public partial class UserController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UserController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected UserController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SignIn() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SignIn);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult HandleFacebookOAuthCallback() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.HandleFacebookOAuthCallback);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UserController Actions { get { return MVC.User; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "User";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "User";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string SignIn = "SignIn";
            public readonly string SignOut = "SignOut";
            public readonly string HandleFacebookOAuthCallback = "HandleFacebookOAuthCallback";
            public readonly string Welcome = "Welcome";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string SignIn = "SignIn";
            public const string SignOut = "SignOut";
            public const string HandleFacebookOAuthCallback = "HandleFacebookOAuthCallback";
            public const string Welcome = "Welcome";
        }


        static readonly ActionParamsClass_SignIn s_params_SignIn = new ActionParamsClass_SignIn();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SignIn SignInParams { get { return s_params_SignIn; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SignIn {
            public readonly string redirectUrl = "redirectUrl";
        }
        static readonly ActionParamsClass_HandleFacebookOAuthCallback s_params_HandleFacebookOAuthCallback = new ActionParamsClass_HandleFacebookOAuthCallback();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_HandleFacebookOAuthCallback HandleFacebookOAuthCallbackParams { get { return s_params_HandleFacebookOAuthCallback; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_HandleFacebookOAuthCallback {
            public readonly string code = "code";
            public readonly string state = "state";
        }
        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string Welcome = "~/Views/User/Welcome.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_UserController: FODT.Controllers.UserController {
        public T4MVC_UserController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult SignIn(string redirectUrl) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SignIn);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "redirectUrl", redirectUrl);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SignOut() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SignOut);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult HandleFacebookOAuthCallback(string code, string state) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.HandleFacebookOAuthCallback);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "code", code);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "state", state);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Welcome() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Welcome);
            return callInfo;
        }

    }
}

namespace T4MVC {
    public class SharedController {

        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            public readonly string MediaItem = "~/Views/Shared/MediaItem.cshtml";
            public readonly string MediaItemViewModel = "~/Views/Shared/MediaItemViewModel.cs";
        }
    }

}




#endregion T4MVC
#pragma warning restore 1591

namespace System.Web.Mvc {
    #region ModelUnbinders
    [GeneratedCode("T4MVC", "2.0")]
    public interface IModelUnbinder {
        void UnbindModel(RouteValueDictionary routeValueDictionary, string routeName, object routeValue);
    }
    [GeneratedCode("T4MVC", "2.0")]
    public interface IModelUnbinder<in T> where T : class {
        void UnbindModel(RouteValueDictionary routeValueDictionary, string routeName, T routeValue);
    }
    [GeneratedCode("T4MVC", "2.0")]
        public class ModelUnbinders {
        private class GenericModelUnbinderWrapper<T> : IModelUnbinder where T : class {
            private readonly IModelUnbinder<T> _unbinder;

            public GenericModelUnbinderWrapper(IModelUnbinder<T> unbinder) {
                _unbinder = unbinder;
            }

            public void UnbindModel(RouteValueDictionary routeValueDictionary, string routeName, object routeValue) {
                var typedObject = routeValue as T;
                _unbinder.UnbindModel(routeValueDictionary, routeName, typedObject);
            }
        }
        
        private readonly Dictionary<Type, IModelUnbinder> _unbinders = new Dictionary<Type, IModelUnbinder>();
        public virtual void Add(Type type, IModelUnbinder unbinder) {
            _unbinders[type] = unbinder;
        }
        public virtual void Add<T>(IModelUnbinder<T> unbinder) where T : class {
            Add(typeof(T), new GenericModelUnbinderWrapper<T>(unbinder));
        }
        public virtual IModelUnbinder FindUnbinderFor(Type type) {
            IModelUnbinder resultUnbinder = null;
            Type baseType = null;
            foreach (var unbinder in _unbinders) {
                if (unbinder.Key.IsAssignableFrom(type)) {
                    if ((baseType == null) || baseType.IsAssignableFrom(unbinder.Key)) {
                        resultUnbinder = unbinder.Value;
                        baseType = unbinder.Key;
                    }
                }
            }
            return resultUnbinder;
        }
        
        public virtual void Clear() {
            _unbinders.Clear();
        }
    }
    [GeneratedCode("T4MVC", "2.0")]
    public class DefaultModelUnbinder : IModelUnbinder {
        public void UnbindModel(RouteValueDictionary routeValueDictionary, string routeName, object routeValue) {
            routeValueDictionary.Add(routeName, routeValue);
        }
    }
    [GeneratedCode("T4MVC", "2.0")]
    public class PropertiesUnbinder : IModelUnbinder {
        public virtual void UnbindModel(RouteValueDictionary routeValueDictionary, string routeName, object routeValue) {
            var dict = new RouteValueDictionary(routeValue);
            foreach (var entry in dict) {
                var name = entry.Key;

                if (!(entry.Value is string) && (entry.Value is System.Collections.IEnumerable)) {
                    var enumerableValue = (System.Collections.IEnumerable)entry.Value;
                    var i = 0;
                    foreach (var enumerableElement in enumerableValue) {
                        ModelUnbinderHelpers.AddRouteValues(routeValueDictionary, string.Format("{0}.{1}[{2}]", routeName, name, i), enumerableElement);
                        i++;
                    }
                }
                else {
                    ModelUnbinderHelpers.AddRouteValues(routeValueDictionary, routeName + "." + name, entry.Value);
                }
            }
        }
    }
    public class ModelUnbinderHelpers {
        public static void AddRouteValues(RouteValueDictionary routeValueDictionary, string routeName, object routeValue) {
            IModelUnbinder unbinder = DefaultModelUnbinder;
            if (routeValue != null)
            {
                unbinder = ModelUnbinders.FindUnbinderFor(routeValue.GetType()) ?? DefaultModelUnbinder;
            }
            unbinder.UnbindModel(routeValueDictionary, routeName, routeValue);
        }
    
        private static readonly ModelUnbinders _modelUnbinders = new ModelUnbinders();
        public static ModelUnbinders ModelUnbinders {
            get { return _modelUnbinders; }
        }

        public static IModelUnbinder DefaultModelUnbinder { get; set; }
        static ModelUnbinderHelpers() {
            DefaultModelUnbinder = new DefaultModelUnbinder();
        }
    }
}
    #endregion




